import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>forex work</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='p-5 m-5 bg-green-500 rounded'>
        <h1 className='text-center'>Appointment</h1>
        <div></div>
      </div>
    </div>
  )
}
